# Generated by Django 4.1.6 on 2023-02-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intervyu',
        ),
    ]
